// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBMessage.proto

package cn.lfyun.network.message;

public final class PBMessageProto {
  private PBMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 cmd = 1;
    /**
     * <code>optional int32 cmd = 1;</code>
     *
     * <pre>
     * 命令
     * </pre>
     */
    boolean hasCmd();
    /**
     * <code>optional int32 cmd = 1;</code>
     *
     * <pre>
     * 命令
     * </pre>
     */
    int getCmd();

    // optional string id = 3;
    /**
     * <code>optional string id = 3;</code>
     *
     * <pre>
     * ID
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional string id = 3;</code>
     *
     * <pre>
     * ID
     * </pre>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 3;</code>
     *
     * <pre>
     * ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // optional int32 status = 4;
    /**
     * <code>optional int32 status = 4;</code>
     *
     * <pre>
     * 状态
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 4;</code>
     *
     * <pre>
     * 状态
     * </pre>
     */
    int getStatus();

    // optional bytes data = 5;
    /**
     * <code>optional bytes data = 5;</code>
     *
     * <pre>
     * 数据
     * </pre>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 5;</code>
     *
     * <pre>
     * 数据
     * </pre>
     */
    com.google.protobuf.ByteString getData();

    // optional int32 sessionId = 6;
    /**
     * <code>optional int32 sessionId = 6;</code>
     *
     * <pre>
     * 唯一的SessionId
     * </pre>
     */
    boolean hasSessionId();
    /**
     * <code>optional int32 sessionId = 6;</code>
     *
     * <pre>
     * 唯一的SessionId
     * </pre>
     */
    int getSessionId();

    // optional bool is_succ = 7;
    /**
     * <code>optional bool is_succ = 7;</code>
     *
     * <pre>
     * 是否成功
     * </pre>
     */
    boolean hasIsSucc();
    /**
     * <code>optional bool is_succ = 7;</code>
     *
     * <pre>
     * 是否成功
     * </pre>
     */
    boolean getIsSucc();

    // optional bool is_return = 8 [default = true];
    /**
     * <code>optional bool is_return = 8 [default = true];</code>
     *
     * <pre>
     * 是否需要应答
     * </pre>
     */
    boolean hasIsReturn();
    /**
     * <code>optional bool is_return = 8 [default = true];</code>
     *
     * <pre>
     * 是否需要应答
     * </pre>
     */
    boolean getIsReturn();
  }
  /**
   * Protobuf type {@code NetProtocol.PBMessage}
   */
  public static final class PBMessage extends
      com.google.protobuf.GeneratedMessage
      implements PBMessageOrBuilder {
    // Use PBMessage.newBuilder() to construct.
    private PBMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBMessage defaultInstance;
    public static PBMessage getDefaultInstance() {
      return defaultInstance;
    }

    public PBMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cmd_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              id_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              status_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              sessionId_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              isSucc_ = input.readBool();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              isReturn_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.lfyun.network.message.PBMessageProto.internal_static_NetProtocol_PBMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.lfyun.network.message.PBMessageProto.internal_static_NetProtocol_PBMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.lfyun.network.message.PBMessageProto.PBMessage.class, cn.lfyun.network.message.PBMessageProto.PBMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<PBMessage> PARSER =
        new com.google.protobuf.AbstractParser<PBMessage>() {
      public PBMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 cmd = 1;
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>optional int32 cmd = 1;</code>
     *
     * <pre>
     * 命令
     * </pre>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 cmd = 1;</code>
     *
     * <pre>
     * 命令
     * </pre>
     */
    public int getCmd() {
      return cmd_;
    }

    // optional string id = 3;
    public static final int ID_FIELD_NUMBER = 3;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 3;</code>
     *
     * <pre>
     * ID
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string id = 3;</code>
     *
     * <pre>
     * ID
     * </pre>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 3;</code>
     *
     * <pre>
     * ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 status = 4;
    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>optional int32 status = 4;</code>
     *
     * <pre>
     * 状态
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 status = 4;</code>
     *
     * <pre>
     * 状态
     * </pre>
     */
    public int getStatus() {
      return status_;
    }

    // optional bytes data = 5;
    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 5;</code>
     *
     * <pre>
     * 数据
     * </pre>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes data = 5;</code>
     *
     * <pre>
     * 数据
     * </pre>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    // optional int32 sessionId = 6;
    public static final int SESSIONID_FIELD_NUMBER = 6;
    private int sessionId_;
    /**
     * <code>optional int32 sessionId = 6;</code>
     *
     * <pre>
     * 唯一的SessionId
     * </pre>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 sessionId = 6;</code>
     *
     * <pre>
     * 唯一的SessionId
     * </pre>
     */
    public int getSessionId() {
      return sessionId_;
    }

    // optional bool is_succ = 7;
    public static final int IS_SUCC_FIELD_NUMBER = 7;
    private boolean isSucc_;
    /**
     * <code>optional bool is_succ = 7;</code>
     *
     * <pre>
     * 是否成功
     * </pre>
     */
    public boolean hasIsSucc() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool is_succ = 7;</code>
     *
     * <pre>
     * 是否成功
     * </pre>
     */
    public boolean getIsSucc() {
      return isSucc_;
    }

    // optional bool is_return = 8 [default = true];
    public static final int IS_RETURN_FIELD_NUMBER = 8;
    private boolean isReturn_;
    /**
     * <code>optional bool is_return = 8 [default = true];</code>
     *
     * <pre>
     * 是否需要应答
     * </pre>
     */
    public boolean hasIsReturn() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool is_return = 8 [default = true];</code>
     *
     * <pre>
     * 是否需要应答
     * </pre>
     */
    public boolean getIsReturn() {
      return isReturn_;
    }

    private void initFields() {
      cmd_ = 0;
      id_ = "";
      status_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      sessionId_ = 0;
      isSucc_ = false;
      isReturn_ = true;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, status_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, sessionId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(7, isSucc_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(8, isReturn_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, status_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, sessionId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isSucc_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, isReturn_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cn.lfyun.network.message.PBMessageProto.PBMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.lfyun.network.message.PBMessageProto.PBMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.lfyun.network.message.PBMessageProto.PBMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.lfyun.network.message.PBMessageProto.PBMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.lfyun.network.message.PBMessageProto.PBMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.lfyun.network.message.PBMessageProto.PBMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cn.lfyun.network.message.PBMessageProto.PBMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cn.lfyun.network.message.PBMessageProto.PBMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cn.lfyun.network.message.PBMessageProto.PBMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cn.lfyun.network.message.PBMessageProto.PBMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.lfyun.network.message.PBMessageProto.PBMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetProtocol.PBMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements cn.lfyun.network.message.PBMessageProto.PBMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.lfyun.network.message.PBMessageProto.internal_static_NetProtocol_PBMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.lfyun.network.message.PBMessageProto.internal_static_NetProtocol_PBMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.lfyun.network.message.PBMessageProto.PBMessage.class, cn.lfyun.network.message.PBMessageProto.PBMessage.Builder.class);
      }

      // Construct using cn.lfyun.network.message.PBMessageProto.PBMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        sessionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        isSucc_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        isReturn_ = true;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.lfyun.network.message.PBMessageProto.internal_static_NetProtocol_PBMessage_descriptor;
      }

      public cn.lfyun.network.message.PBMessageProto.PBMessage getDefaultInstanceForType() {
        return cn.lfyun.network.message.PBMessageProto.PBMessage.getDefaultInstance();
      }

      public cn.lfyun.network.message.PBMessageProto.PBMessage build() {
        cn.lfyun.network.message.PBMessageProto.PBMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.lfyun.network.message.PBMessageProto.PBMessage buildPartial() {
        cn.lfyun.network.message.PBMessageProto.PBMessage result = new cn.lfyun.network.message.PBMessageProto.PBMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.isSucc_ = isSucc_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.isReturn_ = isReturn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.lfyun.network.message.PBMessageProto.PBMessage) {
          return mergeFrom((cn.lfyun.network.message.PBMessageProto.PBMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.lfyun.network.message.PBMessageProto.PBMessage other) {
        if (other == cn.lfyun.network.message.PBMessageProto.PBMessage.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000002;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasSessionId()) {
          setSessionId(other.getSessionId());
        }
        if (other.hasIsSucc()) {
          setIsSucc(other.getIsSucc());
        }
        if (other.hasIsReturn()) {
          setIsReturn(other.getIsReturn());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.lfyun.network.message.PBMessageProto.PBMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.lfyun.network.message.PBMessageProto.PBMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 cmd = 1;
      private int cmd_ ;
      /**
       * <code>optional int32 cmd = 1;</code>
       *
       * <pre>
       * 命令
       * </pre>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 cmd = 1;</code>
       *
       * <pre>
       * 命令
       * </pre>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>optional int32 cmd = 1;</code>
       *
       * <pre>
       * 命令
       * </pre>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cmd = 1;</code>
       *
       * <pre>
       * 命令
       * </pre>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 0;
        onChanged();
        return this;
      }

      // optional string id = 3;
      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 3;</code>
       *
       * <pre>
       * ID
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string id = 3;</code>
       *
       * <pre>
       * ID
       * </pre>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 3;</code>
       *
       * <pre>
       * ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 3;</code>
       *
       * <pre>
       * ID
       * </pre>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 3;</code>
       *
       * <pre>
       * ID
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 3;</code>
       *
       * <pre>
       * ID
       * </pre>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }

      // optional int32 status = 4;
      private int status_ ;
      /**
       * <code>optional int32 status = 4;</code>
       *
       * <pre>
       * 状态
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 status = 4;</code>
       *
       * <pre>
       * 状态
       * </pre>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 4;</code>
       *
       * <pre>
       * 状态
       * </pre>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 4;</code>
       *
       * <pre>
       * 状态
       * </pre>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        onChanged();
        return this;
      }

      // optional bytes data = 5;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 5;</code>
       *
       * <pre>
       * 数据
       * </pre>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes data = 5;</code>
       *
       * <pre>
       * 数据
       * </pre>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 5;</code>
       *
       * <pre>
       * 数据
       * </pre>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 5;</code>
       *
       * <pre>
       * 数据
       * </pre>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // optional int32 sessionId = 6;
      private int sessionId_ ;
      /**
       * <code>optional int32 sessionId = 6;</code>
       *
       * <pre>
       * 唯一的SessionId
       * </pre>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 sessionId = 6;</code>
       *
       * <pre>
       * 唯一的SessionId
       * </pre>
       */
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <code>optional int32 sessionId = 6;</code>
       *
       * <pre>
       * 唯一的SessionId
       * </pre>
       */
      public Builder setSessionId(int value) {
        bitField0_ |= 0x00000010;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sessionId = 6;</code>
       *
       * <pre>
       * 唯一的SessionId
       * </pre>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sessionId_ = 0;
        onChanged();
        return this;
      }

      // optional bool is_succ = 7;
      private boolean isSucc_ ;
      /**
       * <code>optional bool is_succ = 7;</code>
       *
       * <pre>
       * 是否成功
       * </pre>
       */
      public boolean hasIsSucc() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool is_succ = 7;</code>
       *
       * <pre>
       * 是否成功
       * </pre>
       */
      public boolean getIsSucc() {
        return isSucc_;
      }
      /**
       * <code>optional bool is_succ = 7;</code>
       *
       * <pre>
       * 是否成功
       * </pre>
       */
      public Builder setIsSucc(boolean value) {
        bitField0_ |= 0x00000020;
        isSucc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_succ = 7;</code>
       *
       * <pre>
       * 是否成功
       * </pre>
       */
      public Builder clearIsSucc() {
        bitField0_ = (bitField0_ & ~0x00000020);
        isSucc_ = false;
        onChanged();
        return this;
      }

      // optional bool is_return = 8 [default = true];
      private boolean isReturn_ = true;
      /**
       * <code>optional bool is_return = 8 [default = true];</code>
       *
       * <pre>
       * 是否需要应答
       * </pre>
       */
      public boolean hasIsReturn() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool is_return = 8 [default = true];</code>
       *
       * <pre>
       * 是否需要应答
       * </pre>
       */
      public boolean getIsReturn() {
        return isReturn_;
      }
      /**
       * <code>optional bool is_return = 8 [default = true];</code>
       *
       * <pre>
       * 是否需要应答
       * </pre>
       */
      public Builder setIsReturn(boolean value) {
        bitField0_ |= 0x00000040;
        isReturn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_return = 8 [default = true];</code>
       *
       * <pre>
       * 是否需要应答
       * </pre>
       */
      public Builder clearIsReturn() {
        bitField0_ = (bitField0_ & ~0x00000040);
        isReturn_ = true;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetProtocol.PBMessage)
    }

    static {
      defaultInstance = new PBMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetProtocol.PBMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetProtocol_PBMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetProtocol_PBMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017PBMessage.proto\022\013NetProtocol\"\177\n\tPBMess" +
      "age\022\013\n\003cmd\030\001 \001(\005\022\n\n\002id\030\003 \001(\t\022\016\n\006status\030\004" +
      " \001(\005\022\014\n\004data\030\005 \001(\014\022\021\n\tsessionId\030\006 \001(\005\022\017\n" +
      "\007is_succ\030\007 \001(\010\022\027\n\tis_return\030\010 \001(\010:\004trueB" +
      "+\n\027cn.lfyun.network.messageB\016PBMessagePro" +
      "toH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NetProtocol_PBMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NetProtocol_PBMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetProtocol_PBMessage_descriptor,
              new java.lang.String[] { "Cmd", "Id", "Status", "Data", "SessionId", "IsSucc", "IsReturn", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
